### ISSUE TITLE
vignette step fails due to missing SG-tSNE libs

### ISSUE THREAD

**Issue by razofz** [parashardhapola/scarf#35]
I noticed that when building the docs page, cell 20 and 21 of the basic workflow vignette failed:

```
ERROR: SG-tSNE failed, possibly due to missing libraries or file permissions. SG-tSNE currently fails on readthedocs
```

And it also fail on readthedocs. Judging from the output error, you're probably already aware of this :) It works if one installs the current version from PyPI (0.7.7), but not when installing from the current source code (and on readthedocs, as seen above).

I saw some commit where you removed the sgtsne libs from the repo, do you have a plan to handle this in another way or should we discuss possibilities?

**Comment by parashardhapola** [comment]
Good point. It doesn't work on readthedocs because the some of the shared libraries that SG-tSNE needs are missing on their build server. There is currently  no way to fix this. These libs are already mentioned in the DOCKER file in the repo root.

I'm surprised that it fails on current source code as well. Can you debug this and find out why it is failing on your local machine when you pull the latest code?

Yes, I removed the sgtsne libs from the repo. They were added in the first place as a naïve attempt to fix the missing libraries issue with readthedocs. But obviously it didn't work and I rolled back the inclusion of those lib into the repo.

The long term solution for this is upstream on SG-tSNE end. I have had discussions with SG-tSNE devs and they are planning to develop a conda/pip installable version of SG-tSNE. When this happens, Scarf will need not distribute precompiled SG-tSNE execs anymore.

**Comment by parashardhapola** [comment]
For others who end up here due to SG-tSNE error on Linux machine. You will need to run the following on your terminal to install the necessary libraries:

```
TZ="Europe/Stockholm"
DEBIAN_FRONTEND="noninteractive"
sudo apt-get -y install tzdata
sudo ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone &
sudo apt install -y libmetis-dev libtbb-dev libfftw3-dev lib32gcc-7-dev libflann-dev libcilkrts5
```

These are tested for Ubuntu 20.04 but may work on other Ubuntu systems as well. You will need to modify these if you are on some other distro.
