### ISSUE TITLE
Normalization of ADTs on merged datasets

### ISSUE THREAD

**Issue by rwarfvinge** [parashardhapola/scarf#58]
In a merged data set of sample A and B. 
If I color the umap based on the normed ADT expression as written below..

ds.plot_layout(layout_key='RNA_UMAP', from_assay='ADT', color_by= f"ADT_X", cmap='coolwarm', clip_fraction=0.05, cell_key = "I")

...the full sample (cell_key ="I") looks ok.
But if I set cell_key = sample A or sample B separately the expression is lost for sample A. 
Could something be off with the ADT normalization when you split the data set with cell_key?

Thanks!

**Comment by parashardhapola** [comment]
Hi @rwarfvinge

I'm investigating this. Can you please provide some example plots here so that it is easier for me to understand the aberrant behavior that you notice?

**Comment by rwarfvinge** [comment]
Thanks for looking into this,
Here is sample 1 colored by ADT CD54 in a umap by itself
![sample1](https://user-images.githubusercontent.com/71876333/135242175-0acd8c01-e017-4e00-a063-b18c99a96b11.png)

The merged dataset colored by ADT CD54 with cell_key = sample 1:
![merged_sample1](https://user-images.githubusercontent.com/71876333/135242293-3f957d37-d2f2-4305-91d7-4f9ccef7f3f3.png)

The merged dataset colored by ADT CD54 with cell_key = sample 2:
![merged_sample2](https://user-images.githubusercontent.com/71876333/135242557-21df521c-bca6-42b0-b473-c7dc874bca56.png)

The merged dataset colored by ADT CD54 with cell_key = "I" (both):
![merged_both](https://user-images.githubusercontent.com/71876333/135242624-b8a50119-b54b-4171-b996-98f1ef28303c.png)

Same plotting settings are used, so why does cell_key = sample 1 looks so different compared to sample 1 by itself?

**Comment by parashardhapola** [comment]
Interesting. I'm not sure if the issue is with the plotting or the normalization itself. We will check it systematically. First, let's check if  `subselection_key` is helpful. Can you try plotting individual samples using the  `subselection_key` instead of `cell_key` parameter? You provide the same values to `subselection_key` as you did to `cell_key` parameter

**Comment by rwarfvinge** [comment]
Have now tried as you suggested  and now it looks like this:

Merged dataset, subselection_key = sample1
![merged_sample1](https://user-images.githubusercontent.com/71876333/135344084-a435c287-0ed2-4aed-a66d-265fee70bb86.png)


Merged dataset, subselection_key = sample2
![merged_sample2](https://user-images.githubusercontent.com/71876333/135344090-fb9e8178-f95a-4324-8071-eaeae0d29e4c.png)

Merged dataset no subselection (both
![merged_both](https://user-images.githubusercontent.com/71876333/135344267-dddb4fec-df50-4332-808d-77ec150cab21.png)
)

I think this fixed my issue, it looks much better! So whats the difference of cell_key and subselection_key? When is subselection_key preferred? Only when you visualize ADT data or always? Thanks!

**Comment by parashardhapola** [comment]
`cell_key` will usually generate a different representation of your data, think of it as on-the-fly subsetting. This will affect what parameters are used to normalize the data, etc. In the case of scRNA-Seq data, using either `cell_key` or `subselection_key` here would not have made much of a difference because the normalization of the data is done atomically on individually on cells. This means the values of one cell do not affect any of the other cells. However, this is not the case for ADT, HTO, and even snATAC-Seq data, where values of one cell do affect the others.

As a rule of thumb, use `cell_key` when you want to focus on a subset of data and generally do not want to compare it with anything else. For example, when probing substructures or looking for nested relationships between a subset of cells. 
Use `subselection_key` when you just temporarily want to hide/show a subset of your data, for example, when plotting different samples/batches/cell types, etc.

**Comment by rwarfvinge** [comment]
Thank you for the help and for taking the time to explain!
