### ISSUE TITLE
clusters input for TopACeDo 

### ISSUE THREAD

**Issue by yuhanH** [parashardhapola/scarf#65]
Hi,
I want to use `TopACeDo` to downsample the dataset. It seems that pre-defined clusters are required for `TopACeDo`. 
I am wondering how big clustering methods or resolution value can affect the downsampling cells results.  Thanks.

**Comment by parashardhapola** [comment]
Hi,

Sorry for the slow response here.
Not sure what does 'big clustering methods' mean. Can you please explain that further?

As for the resolution value. Ideally, you want to use a resolution value that is most "ideal" for your dataset. So the idea is to use the resolution value that captures as many cell types as expected. The TopACeDo algorithm is designed to be insensitive to the clustering resolution to "a reasonable degree".

In the latest version of TopACeDo, you **must** use the Paris clustering. This was done because the Paris clustering algorithm creates a complete dendrogram of all the cells and hence it is easier for TopACeDo to detect the nested structures in the data.
Paris clustering (`run_clustering` method) will take in the `n_clusters` parameter that decides the number of clusters to be created.

Happy to discuss this further.

**Comment by yuhanH** [comment]
hi @parashardhapola 
Thanks for your explanation. Very clear! Thanks.

**Comment by stela2502** [comment]
Hi, my approach to a similar problem was to hopelessly overcluster the data (100+ clusters) and then merge clusters if the expression values correlated (pearson or spearman) with > .8 -> .99 (users decision). 
I do not have enough confidence into the density reduction methods to rely on the 2/3D strictures too much.
